"""Notebook 37, the RGB Stage C, against the ways it could quietly become 31 again.

It is generated by patching 31's cells, so the failure mode is a leftover: a
thermal source, a teacher pool that does not exist here, or a name 31 defined
in a cell this one replaced. Each of those runs for minutes on a GPU before it
says anything, and one of them (a stale `SOURCE_WEIGHTS` key) would not fail at
all -- it would train on nothing and report a number.
"""
from __future__ import annotations

import ast
import builtins
import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

NOTEBOOK = ROOT / "notebooks" / "37_aerial_rgb_tracking.ipynb"
# Cells 1 and 2 are IPython magics (`!git`, `!python -m unittest`), which are
# not Python and are not meant to be.
MAGIC_CELLS = {1, 2}


def cells():
    return json.loads(NOTEBOOK.read_text(encoding="utf-8"))["cells"]


def code(index: int) -> str:
    return "".join(cells()[index]["source"])


def whole() -> str:
    return "\n".join("".join(cell["source"]) for cell in cells())


class TestNotebook37(unittest.TestCase):
    def test_every_code_cell_parses(self):
        for index, cell in enumerate(cells()):
            if cell["cell_type"] != "code" or index in MAGIC_CELLS:
                continue
            ast.parse("".join(cell["source"]))

    def test_no_name_is_used_before_something_defines_it(self):
        """The check that catches a leftover from a cell that was replaced.

        Running the notebook to find out costs a GPU session; this costs
        milliseconds and found four real breaks the first time it ran.
        """
        known = set(dir(builtins)) | {"get_ipython", "os", "sys", "Path",
                                      "REPO", "BRANCH"}
        undefined = []
        for index, cell in enumerate(cells()):
            if cell["cell_type"] != "code" or index in MAGIC_CELLS:
                continue
            tree = ast.parse("".join(cell["source"]))
            used = {node.id for node in ast.walk(tree)
                    if isinstance(node, ast.Name)
                    and isinstance(node.ctx, ast.Load)}
            for node in ast.walk(tree):
                if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                    known.add(node.id)
                elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    known.add(node.name)
                    known |= {a.arg for a in node.args.args}
                    known |= {a.arg for a in node.args.kwonlyargs}
                elif isinstance(node, ast.ClassDef):
                    known.add(node.name)
                elif isinstance(node, ast.arg):
                    known.add(node.arg)
                elif isinstance(node, (ast.Import, ast.ImportFrom)):
                    for alias in node.names:
                        known.add((alias.asname or alias.name).split(".")[0])
                elif isinstance(node, ast.ExceptHandler) and node.name:
                    known.add(node.name)
            undefined += [f"cell {index}: {name}"
                          for name in sorted(used - known)]
        self.assertEqual(undefined, [])

    def test_no_thermal_source_survived_the_patch(self):
        """VTUAV tracking and BIRDSAI are thermal; Anti-UAV410 is the wrong
        perspective entirely. A leftover reference is a crash at best."""
        body = whole()
        for token in ("VTUAV_ARCHIVES", "USE_ANTIUAV410", "ANTI_DATA",
                      "birdsai_sequences", "vtuav_sequences(",
                      "TEMPORAL_POOL_ROOT", "pool_sequence_stores",
                      "MIN_TEACHER_MASK_FRAMES"):
            self.assertNotIn(token, body, f"{token} is 31's, not 37's")

    def test_the_only_source_weight_is_the_one_source(self):
        """`weighted_clip_sample` samples by source name. A key naming a source
        that is not in the run takes its share of the pool and returns nothing,
        which is a smaller training set and no error."""
        self.assertIn('SOURCE_WEIGHTS = {"vtuav_vis": 1.0}', code(4))

    def test_the_held_out_split_comes_from_the_archives_not_a_hash(self):
        body = code(8)
        self.assertIn("hold_out=held_sequences", body)
        self.assertIn("test_fraction=0.0", body)

    def test_train_and_hold_out_are_checked_for_a_shared_name(self):
        """VTUAV-VIS sequence counters restart per archive, so `train_003`
        exists inside `test_001.zip`. If the parts were unpacked flat the names
        would not carry the part and the held-out set would not be held out."""
        self.assertIn("_overlap", code(8))
        self.assertIn("held-out held-out değildir", code(8))

    def test_it_reads_rgb_frames_and_rgb_masks_together(self):
        self.assertIn('MODALITY = "rgb"', code(4))
        self.assertIn("modality=MODALITY", code(8))

    def test_the_base_is_35s_output(self):
        self.assertIn("pretrain_rgb_aerial", code(4))
        self.assertIn("BASE_STAGE_B_OVERRIDE", code(4))

    def test_its_outputs_do_not_collide_with_31s(self):
        """Two Stage C runs writing one folder means the second overwrites the
        first without a word."""
        body = code(4)
        self.assertIn("aerial_rgb_tracking_from_", body)
        self.assertNotIn("aerial_thermal_tracking", body)

    def test_it_refuses_in_the_first_cell_when_edgetam_is_missing(self):
        """The failure that cost a run: `import sam2` raised at the precheck,
        after Drive was mounted, 126 GB of archives were staged and the split
        was built. Nothing between cell 1 and there needs EdgeTAM, so the check
        belongs in cell 1 where it costs seconds."""
        runtime = code(1)
        self.assertIn("import sam2", runtime)
        self.assertIn("third_party", runtime)
        self.assertIn("SystemExit", runtime)

    def test_it_trains_at_the_size_it_deploys_at(self):
        """VTUAV-VIS is 1920x1080, so `_window_for` takes a native 768 crop
        with no resampling -- the thermal sources cannot, which is why 31 is
        512 and this is not. Training at 512 and deploying at 768 would leave a
        variable nobody measured."""
        self.assertIn("SIZE, CLIP_LEN, CLIP_STRIDE = 768", code(4))

    def test_two_sizes_do_not_write_to_one_folder(self):
        """A 512 run and a 768 run of this notebook are different models."""
        self.assertIn('f"aerial_rgb_tracking_from_{BASE_TAG}_{SIZE}"', code(4))

    def test_the_stock_arm_is_on(self):
        """Stock EdgeTAM is in-domain on RGB, which makes this the comparison
        that matters most here -- and the one it is easiest to lose."""
        self.assertIn("PRECHECK_AGAINST_STOCK = True", code(4))

    def test_it_previews_a_real_run_of_frames_not_only_sheets(self):
        """The contact sheets sample around transitions; they cannot show
        whether the masks hold together in between. Watching a consecutive run
        is the only thing that does, and it has to be in the notebook where
        the data actually is."""
        body = code(10)
        self.assertIn("PREVIEW_RUN", body)
        self.assertIn("preview(", body)
        self.assertIn("PREVIEW_RUN = True", code(4))

    def test_it_says_this_run_has_no_disappearances(self):
        """`vtuav_vis_sequences` sets `exist=np.ones`. Nothing here trains or
        measures the object-score head, and a reader must not have to derive
        that from a function body."""
        self.assertIn("kaybolma denetimi", whole())


if __name__ == "__main__":
    unittest.main()
