"""EdgeTAM backed by a TensorRT image-encoder engine.

Why only the image encoder?
    The image encoder dominates per-frame cost (RepViT backbone + FPN neck).
    The memory module and mask decoder are lightweight and have dynamic
    shapes that are awkward to export — keeping them in PyTorch keeps the
    integration small and side-effect-free.

How:
    1. Build the regular PyTorch EdgeTAM predictor.
    2. Replace `predictor.image_encoder.forward` with a method that calls
       the TRT engine and reconstructs the dict the rest of EdgeTAM expects.
       Positional encodings are regenerated by the original FPN neck's
       PositionEmbeddingSine on each level (deterministic, cheap).

Falls back to plain EdgeTAM if `engine_path` is missing or `tensorrt` is
not importable — useful on dev machines.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterator

from ..prompts import PromptSet
from .base import TrackingResult, VideoTracker
from .edgetam_tracker import EdgeTAMTracker
from .registry import register


@register("edgetam_trt")
class EdgeTAMTRTTracker(EdgeTAMTracker):
    def __init__(
        self,
        engine_path: str,
        model_cfg: str,
        checkpoint: str,
        device: str = "cuda",
        fp16: bool = True,
        mask_threshold: float = 0.0,
        strict: bool = False,
    ) -> None:
        super().__init__(
            model_cfg=model_cfg,
            checkpoint=checkpoint,
            device=device,
            fp16=fp16,
            mask_threshold=mask_threshold,
        )
        self.engine_path = engine_path
        self.strict = strict
        self._trt_engine = None

    def _try_load_engine(self) -> bool:
        try:
            from ._trt_runtime import TRTImageEncoder
        except ImportError as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] tensorrt unavailable ({e}); falling back to PyTorch.")
            return False
        engine_path = Path(self.engine_path)
        if not engine_path.exists():
            if self.strict:
                raise FileNotFoundError(engine_path)
            print(f"[edgetam_trt] engine not found at {engine_path}; falling back to PyTorch.")
            return False
        try:
            self._trt_engine = TRTImageEncoder(engine_path)
            return True
        except Exception as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] engine load failed ({e}); falling back to PyTorch.")
            return False

    def _patch_image_encoder(self) -> None:
        if self._trt_engine is None:
            return
        predictor = self._predictor
        encoder = predictor.image_encoder
        scalp = getattr(encoder, "scalp", 1)
        neck_pos = encoder.neck.position_encoding
        trt_engine = self._trt_engine

        def trt_forward(image):
            # TRT outputs 3 FPN levels (high-res s0, s1, low-res vision_features).
            f0, f1, f2 = trt_engine.infer(image)
            features = [f0, f1, f2]
            # Recompute positional encodings from PyTorch (deterministic, cheap).
            pos = [neck_pos(f).to(f.dtype) for f in features]
            # Re-apply the scalp logic that the original forward does after the neck.
            # Our exported wrapper already kept the last 3 levels, so scalp==1 means
            # no further discard here.
            if scalp > 1:
                features = features[: -(scalp - 1)]
                pos = pos[: -(scalp - 1)]
            return {
                "vision_features": features[-1],
                "vision_pos_enc": pos,
                "backbone_fpn": features,
            }

        # Bind as a bound method.
        encoder.forward = trt_forward  # type: ignore[assignment]
        # `nn.Module.__call__` ultimately calls `.forward`, so this is enough.

    def prepare(self, frames_dir: str | Path) -> None:
        self._ensure_predictor()
        if self._try_load_engine():
            self._patch_image_encoder()
        with self._autocast():
            self._state = self._predictor.init_state(video_path=str(frames_dir))

    # set_prompts / propagate / reset inherited from EdgeTAMTracker.
