"""EdgeTAM backed by a TensorRT image-encoder engine.

Why only the image encoder?
    It dominates per-frame cost (RepViT backbone + FPN neck). The memory
    module and mask decoder are lightweight and have dynamic shapes that
    are awkward to export; keeping them in PyTorch keeps the integration
    small and side-effect-free.

How:
    1. Build the regular PyTorch EdgeTAM predictor.
    2. Replace `predictor.image_encoder.forward` with a method that calls
       the TRT engine and reconstructs the dict the rest of EdgeTAM expects.
       The TRT engine was exported from a wrapper that already applies the
       `scalp` discard — its outputs are the *post-scalp* FPN levels, so
       we do NOT re-apply scalp here.
       Positional encodings are regenerated by the original FPN neck's
       PositionEmbeddingSine on each level (deterministic, cheap).

Falls back to plain EdgeTAM if `engine_path` is missing or `tensorrt` is
not importable — set `strict: true` to forbid that. Benchmarks MUST use
strict mode: a silent fallback reports PyTorch numbers under a TRT label.
"""
from __future__ import annotations

from pathlib import Path

from .edgetam_tracker import EdgeTAMTracker
from .registry import register

_OUTPUT_DTYPES = ("auto", "keep", "float32", "float16", "bfloat16")


@register("edgetam_trt")
class EdgeTAMTRTTracker(EdgeTAMTracker):
    def __init__(
        self,
        engine_path: str,
        model_cfg: str,
        checkpoint: str,
        device: str = "cuda",
        precision: str = "bfloat16",
        mask_threshold: float = 0.0,
        offload_video_to_cpu: bool = False,
        offload_state_to_cpu: bool = False,
        strict: bool = False,
        use_cuda_graph: bool = False,
        trt_synchronize: bool = True,
        trt_output_dtype: str = "auto",
        image_size: int | None = None,
        fill_hole_area: int | None = None,
        cuda_graph_blocks: list[str] | None = None,
    ) -> None:
        super().__init__(
            model_cfg=model_cfg,
            checkpoint=checkpoint,
            device=device,
            precision=precision,
            mask_threshold=mask_threshold,
            offload_video_to_cpu=offload_video_to_cpu,
            offload_state_to_cpu=offload_state_to_cpu,
            image_size=image_size,
            fill_hole_area=fill_hole_area,
            cuda_graph_blocks=cuda_graph_blocks,
        )
        if "image_encoder" in (cuda_graph_blocks or []):
            # The encoder's forward is about to be replaced by the TRT engine.
            # Graphing the engine is `use_cuda_graph` (it lives in the TRT
            # runtime, where the bindings are); a torch graph over it would
            # capture a Python call into TensorRT, which is not capturable.
            raise ValueError(
                "cuda_graph_blocks must not contain 'image_encoder' on the TRT "
                "tracker -- use use_cuda_graph: true instead."
            )
        if trt_output_dtype not in _OUTPUT_DTYPES:
            raise ValueError(
                f"trt_output_dtype must be one of {_OUTPUT_DTYPES} (got {trt_output_dtype})"
            )
        self.engine_path = engine_path
        self.strict = strict
        self.use_cuda_graph = use_cuda_graph
        self.trt_synchronize = trt_synchronize
        self.trt_output_dtype = trt_output_dtype
        self._trt_engine = None
        self.trt_active = False

    def _try_load_engine(self) -> bool:
        try:
            from ._trt_runtime import TRTImageEncoder
        except ImportError as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] tensorrt unavailable ({e}); falling back to PyTorch.")
            return False
        engine_path = Path(self.engine_path)
        if not engine_path.exists():
            if self.strict:
                raise FileNotFoundError(engine_path)
            print(f"[edgetam_trt] engine not found at {engine_path}; falling back to PyTorch.")
            return False
        try:
            self._trt_engine = TRTImageEncoder(
                engine_path,
                use_cuda_graph=self.use_cuda_graph,
                synchronize=self.trt_synchronize,
            )
            return True
        except Exception as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] engine load failed ({e}); falling back to PyTorch.")
            return False

    def _resolved_output_dtype(self):
        """Which dtype the TRT features should be handed back as.

        `auto` keeps the engine's native dtype when autocast is active (the
        downstream convs will cast anyway) but promotes to float32 when it is
        not — an fp16 engine feeding fp32 conv weights outside autocast raises
        a dtype mismatch in `sam_mask_decoder.conv_s0`.
        """
        import torch

        if self.trt_output_dtype == "keep":
            return None
        if self.trt_output_dtype == "auto":
            return torch.float32 if self.precision == "float32" else None
        return {"float32": torch.float32,
                "float16": torch.float16,
                "bfloat16": torch.bfloat16}[self.trt_output_dtype]

    def _patch_image_encoder(self) -> None:
        if self._trt_engine is None:
            return
        encoder = self._predictor.image_encoder
        neck_pos = encoder.neck.position_encoding
        trt_engine = self._trt_engine
        cast_to = self._resolved_output_dtype()

        def trt_forward(image):
            # TRT engine outputs the same tensors the wrapper returned at
            # export time: post-scalp FPN levels. No scalp re-application.
            features = list(trt_engine.infer(image))
            if cast_to is not None:
                features = [f.to(cast_to) for f in features]
            # Recompute positional encodings in PyTorch (deterministic, cheap).
            pos = [neck_pos(f).to(f.dtype) for f in features]
            return {
                "vision_features": features[-1],
                "vision_pos_enc": pos,
                "backbone_fpn": features,
            }

        encoder.forward = trt_forward  # type: ignore[assignment]
        self.trt_active = True

    def prepare(self, frames_dir: str | Path) -> None:
        self._ensure_predictor()
        if self._try_load_engine():
            self._patch_image_encoder()
        if self.device == "cuda":
            for name in self.cuda_graph_blocks:
                self._graph_block(name)
        with self._inference_ctx():
            self._state = self._predictor.init_state(
                video_path=str(frames_dir),
                offload_video_to_cpu=self.offload_video_to_cpu,
                offload_state_to_cpu=self.offload_state_to_cpu,
            )

    # set_prompts / propagate / reset inherited from EdgeTAMTracker.
