"""EdgeTAM backed by a TensorRT image-encoder engine.

Why only the image encoder?
    It dominates per-frame cost (RepViT backbone + FPN neck). The memory
    module and mask decoder are lightweight and have dynamic shapes that
    are awkward to export; keeping them in PyTorch keeps the integration
    small and side-effect-free.

How:
    1. Build the regular PyTorch EdgeTAM predictor.
    2. Replace `predictor.image_encoder.forward` with a method that calls
       the TRT engine and reconstructs the dict the rest of EdgeTAM expects.
       The TRT engine was exported from a wrapper that already applies the
       `scalp` discard — its outputs are the *post-scalp* FPN levels, so
       we do NOT re-apply scalp here.
       Positional encodings are regenerated by the original FPN neck's
       PositionEmbeddingSine on each level (deterministic, cheap).

Falls back to plain EdgeTAM if `engine_path` is missing or `tensorrt` is
not importable.
"""
from __future__ import annotations

from pathlib import Path

from .edgetam_tracker import EdgeTAMTracker
from .registry import register


@register("edgetam_trt")
class EdgeTAMTRTTracker(EdgeTAMTracker):
    def __init__(
        self,
        engine_path: str,
        model_cfg: str,
        checkpoint: str,
        device: str = "cuda",
        precision: str = "bfloat16",
        mask_threshold: float = 0.0,
        offload_video_to_cpu: bool = False,
        offload_state_to_cpu: bool = False,
        strict: bool = False,
    ) -> None:
        super().__init__(
            model_cfg=model_cfg,
            checkpoint=checkpoint,
            device=device,
            precision=precision,
            mask_threshold=mask_threshold,
            offload_video_to_cpu=offload_video_to_cpu,
            offload_state_to_cpu=offload_state_to_cpu,
        )
        self.engine_path = engine_path
        self.strict = strict
        self._trt_engine = None

    def _try_load_engine(self) -> bool:
        try:
            from ._trt_runtime import TRTImageEncoder
        except ImportError as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] tensorrt unavailable ({e}); falling back to PyTorch.")
            return False
        engine_path = Path(self.engine_path)
        if not engine_path.exists():
            if self.strict:
                raise FileNotFoundError(engine_path)
            print(f"[edgetam_trt] engine not found at {engine_path}; falling back to PyTorch.")
            return False
        try:
            self._trt_engine = TRTImageEncoder(engine_path)
            return True
        except Exception as e:
            if self.strict:
                raise
            print(f"[edgetam_trt] engine load failed ({e}); falling back to PyTorch.")
            return False

    def _patch_image_encoder(self) -> None:
        if self._trt_engine is None:
            return
        encoder = self._predictor.image_encoder
        neck_pos = encoder.neck.position_encoding
        trt_engine = self._trt_engine

        def trt_forward(image):
            # TRT engine outputs the same tensors the wrapper returned at
            # export time: post-scalp FPN levels. No scalp re-application.
            f0, f1, f2 = trt_engine.infer(image)
            features = [f0, f1, f2]
            # Recompute positional encodings in PyTorch (deterministic, cheap).
            pos = [neck_pos(f).to(f.dtype) for f in features]
            return {
                "vision_features": features[-1],
                "vision_pos_enc": pos,
                "backbone_fpn": features,
            }

        encoder.forward = trt_forward  # type: ignore[assignment]

    def prepare(self, frames_dir: str | Path) -> None:
        self._ensure_predictor()
        if self._try_load_engine():
            self._patch_image_encoder()
        with self._inference_ctx():
            self._state = self._predictor.init_state(
                video_path=str(frames_dir),
                offload_video_to_cpu=self.offload_video_to_cpu,
                offload_state_to_cpu=self.offload_state_to_cpu,
            )

    # set_prompts / propagate / reset inherited from EdgeTAMTracker.
